### ISSUE TITLE
Add Favicon to web page

### ISSUE THREAD

**Issue by newdeal123** [ArgoWorkflows-OSS/argoworkflows-oss.github.io#53]
**Is your feature request related to a problem? Please describe.**
<img width="1247" alt="image" src="https://github.com/ArgoWorkflows-OSS/argoworkflows-oss.github.io/assets/31841502/64c91cc5-17ba-48e8-8b60-d6b5e871efcc">
When I access the web page, I don't see the Favicon. 😡

**Describe the solution you'd like**
Add Favicon like this.
<img width="52" alt="image" src="https://github.com/ArgoWorkflows-OSS/argoworkflows-oss.github.io/assets/31841502/0cf505a0-2e82-489f-a2bf-f5e0d12a0ba4">

**Describe alternatives you've considered**
-

**Additional context**
LGTM 😎

**Comment by GeunSam2** [comment]
Good Issue! Are you interest in this issue??

**Comment by newdeal123** [comment]
YES, I want to work on it. Can I get the file of the channel image in our Slack?

**Comment by GeunSam2** [comment]
are u there?
